name: Check and Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-brew:
    runs-on: macos-latest
    steps:
    - name: Set Version Variable
      run: echo "HDR_RESIZE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Setup Git Credentials
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      run: |
        SSH_PATH="$HOME/.ssh"
        mkdir -p "$SSH_PATH"
        echo "$SSH_DEPLOY_KEY" > "$SSH_PATH/deploy_key"
        chmod 600 "$SSH_PATH/deploy_key"
        ssh-keyscan -H "github.com" > "$SSH_PATH/known_hosts"
        echo "GIT_SSH_COMMAND="ssh -vvv -i $SSH_PATH/deploy_key -o UserKnownHostsFile=$SSH_PATH/known_hosts"" >> $GITHUB_ENV
    - name: Clone Personal Homebrew Repo
      env:
        PUSHER_NAME: ${{ github.event.pusher.name }}
        PUSHER_EMAIL: ${{ github.event.pusher.email }}
      run: |
        git config --global user.name "$PUSHER_NAME"
        git config --global user.email "$PUSHER_EMAIL"
        git clone git@github.com:sjml/homebrew-sjml.git homebrew-sjml
    - name: Update Local Tap
      # doing manually since `brew bump-formula-pr` has a long installation and wants a PAT?
      #    probably useful if you want to open a PR to the core Homebrew repo, but we're just
      #    gonna push directly.
      run: |
        wget "https://github.com/sjml/hdr-resize/archive/refs/tags/$HDR_RESIZE_VERSION.tar.gz"
        SHA256_SUM=($(shasum -a 256 $HDR_RESIZE_VERSION.tar.gz))
        cd homebrew-sjml
        sed -i .bak -E "s/(\s*)url (.*)$/\1url \"https:\/\/github.com\/sjml\/hdr-resize\/archive\/refs\/tags\/$HDR_RESIZE_VERSION.tar.gz\"/" Formula/hdr-resize.rb
        sed -i .bak -E "s/(\s*)sha256 (.*)$/\1sha256 \"$SHA256_SUM\"/" Formula/hdr-resize.rb
        rm Formula/*.bak
    - name: Commit and Push to Remote
      run: |
        cd homebrew-sjml
        git add .
        git commit -m "Updating hdr-resize to $HDR_RESIZE_VERSION"
        echo "Pushing to remote..."
        git push
